"""示意库：精选真实 CVPR / ICCV / ECCV 公开论文（含该篇 OA 或 arXiv 链接）。

这不是三大会 2022–2026 的全量爬取。全量请走采集中心（DBLP ee + OpenAlex）。
启动时按固定 id 刷新这些示意条目，不会删除用户另行采集的论文。
"""

from store import delete_paper, list_papers, upsert_paper

OA = "https://openaccess.thecvf.com/content"


def P(pid, title, venue, year, keywords, abstract, link):
    return {
        "id": pid,
        "title": title,
        "venue": venue,
        "year": year,
        "keywords": keywords,
        "abstract": abstract,
        "link": link,
        "source": "seed",
        "status": "complete",
    }


SEED = [
    # 2022 CVPR
    P("p1", "High-Resolution Image Synthesis with Latent Diffusion Models", "CVPR", 2022,
      ["Diffusion Models", "Generative Models"],
      "在潜空间做扩散，成为后续文生图与视觉生成的基础工作之一。",
      f"{OA}/CVPR2022/html/Rombach_High-Resolution_Image_Synthesis_With_Latent_Diffusion_Models_CVPR_2022_paper.html"),
    P("p2", "Masked Autoencoders Are Scalable Vision Learners", "CVPR", 2022,
      ["Self-Supervised Learning", "Vision Transformer"],
      "MAE 用高比例掩码重建验证了 ViT 自监督预训练的可扩展性。",
      f"{OA}/CVPR2022/html/He_Masked_Autoencoders_Are_Scalable_Vision_Learners_CVPR_2022_paper.html"),
    P("p3", "Mip-NeRF 360: Unbounded Anti-Aliased Neural Radiance Fields", "CVPR", 2022,
      ["Neural Radiance Fields", "3D Reconstruction"],
      "把 NeRF 扩展到无界 360° 场景，并处理抗锯齿。",
      f"{OA}/CVPR2022/html/Barron_Mip-NeRF_360_Unbounded_Anti-Aliased_Neural_Radiance_Fields_CVPR_2022_paper.html"),
    P("p4", "MonoScene: Monocular 3D Semantic Scene Completion", "CVPR", 2022,
      ["Occupancy", "Autonomous Driving"],
      "单目语义场景补全，是 occupancy 表示进入驾驶感知的早期代表。",
      f"{OA}/CVPR2022/html/Cao_MonoScene_Monocular_3D_Semantic_Scene_Completion_CVPR_2022_paper.html"),
    P("p5", "SimMIM: A Simple Framework for Masked Image Modeling", "CVPR", 2022,
      ["Self-Supervised Learning", "Vision Transformer"],
      "更简单的掩码图像建模基线，与 MAE 一起构成 2022 自监督主线。",
      f"{OA}/CVPR2022/html/Xie_SimMIM_A_Simple_Framework_for_Masked_Image_Modeling_CVPR_2022_paper.html"),
    P("p6", "Point-NeRF: Point-based Neural Radiance Fields", "CVPR", 2022,
      ["Neural Radiance Fields", "3D Reconstruction"],
      "用点基表示加速神经辐射场重建。",
      f"{OA}/CVPR2022/html/Xu_Point-NeRF_Point-Based_Neural_Radiance_Fields_CVPR_2022_paper.html"),
    # 2022 ECCV
    P("p7", "Simple Baselines for Image Restoration", "ECCV", 2022,
      ["Image Restoration"],
      "NAFNet：用简洁基线讨论图像恢复中的网络与训练。",
      "https://arxiv.org/abs/2204.04676"),
    P("p8", "TensoRF: Tensorial Radiance Fields", "ECCV", 2022,
      ["Neural Radiance Fields", "3D Reconstruction"],
      "张量分解加速辐射场，和 CVPR 的 NeRF 工作形成对照。",
      "https://arxiv.org/abs/2203.09517"),
    P("p9", "BEVFormer: Learning Bird's-Eye-View Representation from Multi-Camera Images via Spatiotemporal Transformers", "ECCV", 2022,
      ["Autonomous Driving", "Occupancy"],
      "多相机时序 Transformer 学 BEV，是驾驶感知的主干之一。",
      "https://arxiv.org/abs/2203.17270"),
    P("p10", "PETR: Position Embedding Transformation for Multi-View 3D Object Detection", "ECCV", 2022,
      ["Autonomous Driving", "Object Detection"],
      "位置编码变换用于多视图 3D 检测。",
      "https://arxiv.org/abs/2203.16554"),
    P("p11", "MaxViT: Multi-Axis Vision Transformer", "ECCV", 2022,
      ["Vision Transformer"],
      "多轴注意力的高效 ViT 骨干。",
      "https://arxiv.org/abs/2204.01697"),
    P("p12", "MCVD: Masked Conditional Video Diffusion for Prediction, Generation, and Interpolation", "ECCV", 2022,
      ["Video Generation", "Diffusion Models"],
      "条件视频扩散，把生成从图像拉到时序。",
      "https://arxiv.org/abs/2205.09853"),
    # 2023 CVPR
    P("p13", "DreamBooth: Fine Tuning Text-to-Image Diffusion Models for Subject-Driven Generation", "CVPR", 2023,
      ["Diffusion Models", "Generative Models"],
      "用极少样本把主体概念写入扩散模型。",
      f"{OA}/CVPR2023/html/Ruiz_DreamBooth_Fine_Tuning_Text-to-Image_Diffusion_Models_for_Subject-Driven_Generation_CVPR_2023_paper.html"),
    P("p14", "InstructPix2Pix: Learning to Follow Image Editing Instructions", "CVPR", 2023,
      ["Diffusion Models", "Generative Models"],
      "按自然语言指令编辑图像。",
      f"{OA}/CVPR2023/html/Brooks_InstructPix2Pix_Learning_to_Follow_Image_Editing_Instructions_CVPR_2023_paper.html"),
    P("p15", "Planning-oriented Autonomous Driving", "CVPR", 2023,
      ["Autonomous Driving", "World Model"],
      "UniAD：以规划为目标统一驾驶感知与预测。",
      f"{OA}/CVPR2023/html/Hu_Planning-Oriented_Autonomous_Driving_CVPR_2023_paper.html"),
    P("p16", "VoxFormer: Sparse Voxel Transformer for Camera-based 3D Semantic Scene Completion", "CVPR", 2023,
      ["Occupancy", "Autonomous Driving"],
      "稀疏体素 Transformer 做相机 occupancy。",
      f"{OA}/CVPR2023/html/Li_VoxFormer_Sparse_Voxel_Transformer_for_Camera-Based_3D_Semantic_Scene_Completion_CVPR_2023_paper.html"),
    P("p17", "InternImage: Exploring Large-Scale Vision Foundation Models with Deformable Convolutions", "CVPR", 2023,
      ["Foundation Model", "Vision Transformer"],
      "可变形卷积规模化视觉基础模型。",
      f"{OA}/CVPR2023/html/Wang_InternImage_Exploring_Large-Scale_Vision_Foundation_Models_with_Deformable_Convolutions_CVPR_2023_paper.html"),
    P("p18", "GLIGEN: Open-Set Grounded Text-to-Image Generation", "CVPR", 2023,
      ["Diffusion Models", "Open-Vocabulary"],
      "把检测框等条件接入文生图扩散。",
      f"{OA}/CVPR2023/html/Li_GLIGEN_Open-Set_Grounded_Text-to-Image_Generation_CVPR_2023_paper.html"),
    P("p19", "OneFormer: One Transformer to Rule Universal Image Segmentation", "CVPR", 2023,
      ["Foundation Model", "Segment Anything"],
      "用一个 Transformer 覆盖多种分割任务。",
      f"{OA}/CVPR2023/html/Jain_OneFormer_One_Transformer_to_Rule_Universal_Image_Segmentation_CVPR_2023_paper.html"),
    # 2023 ICCV
    P("p20", "Segment Anything", "ICCV", 2023,
      ["Segment Anything", "Foundation Model"],
      "可提示分割基础模型 SAM，推动分割进入提示式范式。",
      f"{OA}/ICCV2023/html/Kirillov_Segment_Anything_ICCV_2023_paper.html"),
    P("p21", "Adding Conditional Control to Text-to-Image Diffusion Models", "ICCV", 2023,
      ["Diffusion Models", "Generative Models"],
      "ControlNet：给预训练扩散模型加空间条件控制。",
      f"{OA}/ICCV2023/html/Zhang_Adding_Conditional_Control_to_Text-to-Image_Diffusion_Models_ICCV_2023_paper.html"),
    P("p22", "Scalable Diffusion Models with Transformers", "ICCV", 2023,
      ["Diffusion Models", "Vision Transformer"],
      "DiT 把 Transformer 用作扩散骨干。",
      f"{OA}/ICCV2023/html/Peebles_Scalable_Diffusion_Models_with_Transformers_ICCV_2023_paper.html"),
    P("p23", "SurroundOcc: Multi-Camera 3D Occupancy Prediction for Autonomous Driving", "ICCV", 2023,
      ["Occupancy", "Autonomous Driving"],
      "环视多相机 3D occupancy 预测。",
      f"{OA}/ICCV2023/html/Wei_SurroundOcc_Multi-Camera_3D_Occupancy_Prediction_for_Autonomous_Driving_ICCV_2023_paper.html"),
    P("p24", "Sigmoid Loss for Language Image Pre-Training", "ICCV", 2023,
      ["Foundation Model", "Open-Vocabulary"],
      "SigLIP：sigmoid 损失做图文预训练。",
      f"{OA}/ICCV2023/html/Zhai_Sigmoid_Loss_for_Language_Image_Pre-Training_ICCV_2023_paper.html"),
    P("p25", "Zero-1-to-3: Zero-shot One Image to 3D Object", "ICCV", 2023,
      ["Diffusion Models", "3D Reconstruction"],
      "单张图零样本转到新视角，连接扩散与三维。",
      f"{OA}/ICCV2023/html/Liu_Zero-1-to-3_Zero-shot_One_Image_to_3D_Object_ICCV_2023_paper.html"),
    P("p26", "OccFormer: Dual-path Transformer for Vision-based 3D Semantic Occupancy Prediction", "ICCV", 2023,
      ["Occupancy", "Autonomous Driving"],
      "双路径 Transformer 做视觉 occupancy。",
      f"{OA}/ICCV2023/html/Zhang_OccFormer_Dual-path_Transformer_for_Vision-based_3D_Semantic_Occupancy_Prediction_ICCV_2023_paper.html"),
    # 2024 CVPR
    P("p27", "Depth Anything: Unleashing the Power of Large-Scale Unlabeled Data", "CVPR", 2024,
      ["Depth Estimation", "Foundation Model"],
      "大规模未标注数据训练的单目深度基础模型。",
      f"{OA}/CVPR2024/html/Yang_Depth_Anything_Unleashing_the_Power_of_Large-Scale_Unlabeled_Data_CVPR_2024_paper.html"),
    P("p28", "pixelSplat: 3D Gaussian Splats from Image Pairs for Scalable Generalizable 3D Reconstruction", "CVPR", 2024,
      ["3D Gaussian Splatting", "3D Reconstruction"],
      "从图像对前馈预测三维高斯，泛化式重建。",
      f"{OA}/CVPR2024/html/Charatan_pixelSplat_3D_Gaussian_Splats_from_Image_Pairs_for_Scalable_Generalizable_CVPR_2024_paper.html"),
    P("p29", "2D Gaussian Splatting for Geometrically Accurate Radiance Fields", "CVPR", 2024,
      ["3D Gaussian Splatting", "Neural Radiance Fields"],
      "二维高斯泼溅，强调几何更准的辐射场。",
      f"{OA}/CVPR2024/html/Huang_2D_Gaussian_Splatting_for_Geometrically_Accurate_Radiance_Fields_CVPR_2024_paper.html"),
    P("p30", "Scaffold-GS: Structured 3D Gaussians for View-Adaptive Rendering", "CVPR", 2024,
      ["3D Gaussian Splatting", "3D Reconstruction"],
      "结构化三维高斯，做视角自适应渲染。",
      f"{OA}/CVPR2024/html/Lu_Scaffold-GS_Structured_3D_Gaussians_for_View-Adaptive_Rendering_CVPR_2024_paper.html"),
    P("p31", "InternVL: Scaling up Vision Foundation Models and Aligning for Generic Visual-Linguistic Tasks", "CVPR", 2024,
      ["Multimodal LLM", "Foundation Model"],
      "视觉基础模型规模化并对齐到视觉-语言任务。",
      f"{OA}/CVPR2024/html/Chen_InternVL_Scaling_up_Vision_Foundation_Models_and_Aligning_for_Generic_CVPR_2024_paper.html"),
    P("p32", "Sapiens: Foundation for Human Vision Models", "CVPR", 2024,
      ["Foundation Model", "Segment Anything"],
      "面向人体视觉任务的基础模型。",
      f"{OA}/CVPR2024/html/Khirodkar_Sapiens_Foundation_for_Human_Vision_Models_CVPR_2024_paper.html"),
    P("p33", "PanoOcc: Unified Occupancy Representation for Camera-based 3D Semantic Occupancy Prediction", "CVPR", 2024,
      ["Occupancy", "Autonomous Driving"],
      "统一 occupancy 表示，做相机三维语义占用预测。",
      f"{OA}/CVPR2024/html/Wang_PanoOcc_Unified_Occupancy_Representation_for_Camera-based_3D_Semantic_Occupancy_Prediction_CVPR_2024_paper.html"),
    # 2024 ECCV
    P("p34", "LGM: Large Multi-View Gaussian Model for High-Resolution 3D Content Creation", "ECCV", 2024,
      ["3D Gaussian Splatting", "3D Reconstruction"],
      "多视图大高斯模型做高分辨率三维内容。",
      "https://www.ecva.net/papers/eccv_2024/papers_ECCV/html/465_ECCV_2024_paper.php"),
    P("p35", "InstantMesh: Efficient 3D Mesh Generation from a Single Image with Sparse-view Large Reconstruction Models", "ECCV", 2024,
      ["3D Reconstruction", "3D Gaussian Splatting"],
      "单图稀疏视图快速出网格。",
      "https://arxiv.org/abs/2404.07191"),
    P("p36", "LivePortrait: Efficient Portrait Animation with Stitching and Retargeting Control", "ECCV", 2024,
      ["Video Generation", "Generative Models"],
      "高效人像动画与重定向。",
      "https://arxiv.org/abs/2407.03168"),
    P("p37", "GaussianFormer: Scene as Gaussians for Vision-Based 3D Semantic Occupancy Prediction", "ECCV", 2024,
      ["Occupancy", "3D Gaussian Splatting", "Autonomous Driving"],
      "用高斯表示场景做视觉 occupancy。",
      "https://arxiv.org/abs/2405.17429"),
    # 2025 CVPR
    P("p38", "DepthSplat: Connecting Gaussian Splatting and Depth", "CVPR", 2025,
      ["3D Gaussian Splatting", "Depth Estimation"],
      "把高斯泼溅与深度估计连起来，互相增益。",
      f"{OA}/CVPR2025/html/Xu_DepthSplat_Connecting_Gaussian_Splatting_and_Depth_CVPR_2025_paper.html"),
    P("p39", "VGGT: Visual Geometry Grounded Transformer", "CVPR", 2025,
      ["3D Reconstruction", "Foundation Model"],
      "几何先验接地的视觉 Transformer，服务重建。",
      f"{OA}/CVPR2025/html/Wang_VGGT_Visual_Geometry_Grounded_Transformer_CVPR_2025_paper.html"),
    P("p40", "GaussianFormer-2: Probabilistic Gaussian Superposition for Efficient 3D Occupancy Prediction", "CVPR", 2025,
      ["Occupancy", "3D Gaussian Splatting", "Autonomous Driving"],
      "概率高斯叠加，做高效 occupancy。",
      f"{OA}/CVPR2025/html/Huang_GaussianFormer-2_Probabilistic_Gaussian_Superposition_for_Efficient_3D_Occupancy_Prediction_CVPR_2025_paper.html"),
    # 2025 ICCV
    P("p41", "GaussianOcc: Fully Self-supervised and Efficient 3D Occupancy Estimation with Gaussian Splatting", "ICCV", 2025,
      ["Occupancy", "3D Gaussian Splatting", "Autonomous Driving"],
      "用高斯泼溅做全自监督 occupancy。",
      f"{OA}/ICCV2025/html/Gan_GaussianOcc_Fully_Self-supervised_and_Efficient_3D_Occupancy_Estimation_with_Gaussian_ICCV_2025_paper.html"),
    P("p42", "GS-Occ3D: Scaling Vision-only Occupancy Reconstruction with Gaussian Splatting", "ICCV", 2025,
      ["Occupancy", "3D Gaussian Splatting", "Autonomous Driving"],
      "纯视觉 occupancy 重建，用高斯泼溅做规模化。",
      f"{OA}/ICCV2025/html/Ye_GS-Occ3D_Scaling_Vision-only_Occupancy_Reconstruction_with_Gaussian_Splatting_ICCV_2025_paper.html"),
    P("p43", "GaussianFlowOcc: Sparse and Weakly Supervised Occupancy Estimation using Gaussian Splatting and Temporal Flow", "ICCV", 2025,
      ["Occupancy", "3D Gaussian Splatting", "Autonomous Driving"],
      "稀疏弱监督 occupancy，结合高斯泼溅与时序流。",
      f"{OA}/ICCV2025/html/Boeder_GaussianFlowOcc_Sparse_and_Weakly_Supervised_Occupancy_Estimation_using_Gaussian_Splatting_ICCV_2025_paper.html"),
    P("p44", "GaussRender: Learning 3D Occupancy with Gaussian Rendering", "ICCV", 2025,
      ["Occupancy", "3D Gaussian Splatting", "Autonomous Driving"],
      "用高斯渲染的投影一致性学习 occupancy。",
      f"{OA}/ICCV2025/html/Chambon_GaussRender_Learning_3D_Occupancy_with_Gaussian_Rendering_ICCV_2025_paper.html"),
    # 2026 CVPR（OA 已公开）
    P("p45", "DLWM: Dual Latent World Models enable Holistic Gaussian-centric Pre-training in Autonomous Driving", "CVPR", 2026,
      ["World Model", "3D Gaussian Splatting", "Occupancy", "Autonomous Driving"],
      "双潜空间世界模型，高斯中心的驾驶预训练与 occupancy 预测。",
      f"{OA}/CVPR2026/html/Zhu_DLWM_Dual_Latent_World_Models_enable_Holistic_Gaussian-centric_Pre-training_in_CVPR_2026_paper.html"),
    P("p46", "GaussianDWM: 3D Gaussian Driving World Model for Unified Scene Understanding and Multi-Modal Generation", "CVPR", 2026,
      ["World Model", "3D Gaussian Splatting", "Multimodal LLM", "Autonomous Driving"],
      "三维高斯驾驶世界模型，统一场景理解与多模态生成。",
      f"{OA}/CVPR2026/html/Deng_GaussianDWM_3D_Gaussian_Driving_World_Model_for_Unified_Scene_Understanding_CVPR_2026_paper.html"),
    P("p47", "Deformable Gaussian Occupancy: Decoupling Rigid and Nonrigid Motion with Factorized Distillation", "CVPR", 2026,
      ["Occupancy", "3D Gaussian Splatting", "Autonomous Driving"],
      "可变形高斯 occupancy，解耦刚体与非刚体运动。",
      f"{OA}/CVPR2026/html/Gao_Deformable_Gaussian_Occupancy_Decoupling_Rigid_and_Nonrigid_Motion_with_Factorized_CVPR_2026_paper.html"),
]


def seed_demo():
    """刷新示意条目；用户自己采集、id 不在本表中的论文原样保留。"""
    keep = {item["id"] for item in SEED}
    for item in SEED:
        upsert_paper(item, paper_id=item["id"])
    papers, _ = list_papers()
    for paper in papers:
        if paper.get("source") == "seed" and paper["id"] not in keep:
            delete_paper(paper["id"])
    return len(SEED)


def seed_if_empty():
    return seed_demo()
